Feature/ui
WalkingMachine/sara_ui pull request #4
Opened 2017-05-22 21:51 UTC by lucasmaurice

La feature de log de diagnostics depuis le laptop est terminee ainsi que la feature de lancement de scenarios. Les deux fonctionnent vraiment bien.

Plus de details dans le nouveau Readme.

2017-05-22 23:58 UTC, gzsierra requested changes
Change stuff.
Some stuff can wait for another PR

2017-05-22 23:58 UTC, gzsierra commented on src/helper.cpp
> +	@contact:	lucas.maurice@outlook.com
wrong tab

2017-05-22 23:58 UTC, gzsierra commented on src/helper.cpp
> +
wrong tab

2017-05-22 23:58 UTC, gzsierra commented on src/helper.h
> +/**
Check all the tab

2017-05-22 23:58 UTC, gzsierra commented on src/helper_funct.cpp
> +			ROS_INFO("Could not execute");
`ROS_WARN` should be better than `ROS_INFO`

2017-05-22 23:58 UTC, gzsierra commented on tests/subscribe.cpp
> +[ INFO] [1488949233.661324768]: 0: HDD Usage (djls_desktop)
To remove

2017-05-22 23:58 UTC, gzsierra commented on launch/pi_core_helper.launch
> +	<machine	name="core"	address="192.168.0.118"	user="lucas"	password="mauricel"	env-loader="/opt/ros/kinetic/sara_core.sh"/>
Remove IP
Change for something like : `[INSERT_MASTER_IP]`

2017-05-22 23:58 UTC, gzsierra commented on launch/pi_ui_autolaunch.launch
> +	<machine	name="core"	address="192.168.0.118"	user="lucas"	password="mauricel"	env-loader="/opt/ros/kinetic/sara_core.sh" />	<!-- Core machine		-->
IP

2017-05-22 23:58 UTC, gzsierra commented on launch/pi_ui_autolaunch.launch
> +	<machine	name="core"	address="192.168.0.118"	user="lucas"	password="mauricel"	env-loader="/opt/ros/kinetic/sara_core.sh" />	<!-- Core machine		-->
**`PASSWD`**

2017-05-22 23:58 UTC, gzsierra commented on launcher-debug.sh
> +export ROS_MASTER_URI=http://192.168.0.118:11311/
IP

2017-05-22 23:58 UTC, gzsierra commented on launcher.sh
> +export ROS_MASTER_URI=http://192.168.0.118:11311/
IP

2017-05-22 23:58 UTC, gzsierra commented on launch/pi_core_helper.launch
> +	<machine	name="core"	address="192.168.0.118"	user="lucas"	password="mauricel"	env-loader="/opt/ros/kinetic/sara_core.sh"/>
**`PASSWD`**

2017-05-22 23:58 UTC, gzsierra commented on package.xml
>    <version>0.0.0</version>
`VERSION` -> `0.1.0`

2017-05-22 23:58 UTC, gzsierra commented on sara_core.sh
> +. /home/lucas/sara_ws/devel/setup.sh
`USER_WORKSPACE` -> `lucas`

2017-05-31 22:26 UTC, lucasmaurice commented
@gzsierra All done!

2017-06-09 22:19 UTC, gzsierra requested changes
Small stuff to change
YOU CAN DO IT!!!!!!

2017-06-09 22:19 UTC, gzsierra commented on README.md
> +**Pour lancer l'interface graphique en mode debuguage :**
*debogage*

2017-06-09 22:19 UTC, gzsierra commented on README.md
> +- Pour réccuperé les diagnostics du robot le topic */diagnostics* est utilisé.
*récupérer*

2017-06-09 22:19 UTC, gzsierra commented on README.md
> +- Pour executer les scenarios, c'est le topic */sara_launch* qui est utilisé. */-Supposément--\\*
*scénarios*

2017-06-09 22:19 UTC, gzsierra commented on README.md
> +**lm-sensors** pour reccuperer les temperatures sur le Pc avec *sensors*
*récupérer*

2017-06-09 22:19 UTC, gzsierra commented on sara_ui.pro.user
> +    <value type="QString" key="ProjectExplorer.BuildConfiguration.BuildDirectory">/home/lucas/sara_qt/src/sara_qt/sara_qt_test1/build-sara_ui-Desktop_Qt_5_8_0_GCC_64bit-Debug</value>
`/home/lucas`
*sara_ui*

2017-06-09 22:19 UTC, gzsierra commented on src/mainwindow.cpp
> +//	 delete this;
Well you can do it!

2017-06-12 18:14 UTC, lucasmaurice commented on sara_ui.pro.user
> +    <value type="QString" key="ProjectExplorer.BuildConfiguration.BuildDirectory">/home/lucas/sara_qt/src/sara_qt/sara_qt_test1/build-sara_ui-Desktop_Qt_5_8_0_GCC_64bit-Debug</value>
C'est un fichier de projet, c'est pour ça qu'il y a des liens absolus.

2017-06-12 18:31 UTC, lucasmaurice commented
Done!

2017-06-15 05:12 UTC, lucasmaurice commented
Il y a un soucis dans mon application, je ferme donc la PR.

2017-06-15 05:12 UTC, closed without merging